#!/usr/bin/env bash

function _nodeenv_profile {
  local shome="${_nodeenv_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  NODEENV_VERSION="$(cat "$shome/.nodeenv-version.json" | jq -r '.[].version')"
}

_nodeenv_profile
