#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_nodeenv="$(nodeenv --version 2>/dev/null || true)"
  jq -n \
    --arg nodeenv "$ver_nodeenv" \
      '{nodeenv: $nodeenv}'
}

version "$@"
